name: Run Tests in Docker

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-in-docker:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Скачиваем код из репозитория на сервер
      - name: Checkout Code
        uses: actions/checkout@v4

      # Шаг 2: Запускаем тесты через Docker Compose
      # Обрати внимание: 'docker compose' без дефиса!
      - name: Run Tests via Docker Compose
        # Указываем папку, где лежит docker-compose.yml
        working-directory: ./DockerTests
        run: |
          docker compose up --build --abort-on-container-exit --exit-code-from tests